name: frame_vision
description: "Foundation for Frame Vision apps. Takes repeated snapshots and feeds into a machine vision pipeline."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.7
  google_mlkit_barcode_scanning: ^0.12.0
  image: ^4.2.0
  logging: ^1.2.0
  convert_native_img_stream: ^0.0.1
  google_mlkit_commons: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/battery.min.lua
    - assets/camera.min.lua
    - assets/data.min.lua
    - assets/frame_app.min.lua